-- MySQL Script generated by MySQL Workbench
-- Mon May  2 20:54:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`NFT_attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NFT_attributes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trait1` VARCHAR(45) NULL,
  `value1` VARCHAR(45) NULL,
  `trait2` VARCHAR(45) NULL,
  `value2` VARCHAR(45) NULL,
  `trait3` VARCHAR(45) NULL,
  `value3` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NFT_metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NFT_metadata` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `data_url` VARCHAR(45) NULL,
  `tokenType` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `NFT_attributes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_NFT_metadata_NFT_attributes`
    FOREIGN KEY (`NFT_attributes_id`)
    REFERENCES `mydb`.`NFT_attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_NFT_metadata_NFT_attributes_idx` ON `mydb`.`NFT_metadata` (`NFT_attributes_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`NFT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NFT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_address` VARCHAR(45) NULL,
  `NFT_metadata_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_NFT_NFT_metadata1`
    FOREIGN KEY (`NFT_metadata_id`)
    REFERENCES `mydb`.`NFT_metadata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_NFT_NFT_metadata1_idx` ON `mydb`.`NFT` (`NFT_metadata_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`NFT_attributes`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`NFT_attributes` (`id`, `trait1`, `value1`, `trait2`, `value2`, `trait3`, `value3`) VALUES (0, 'BACKGROUND', 'BABY_BLUE', 'BASE', 'WHITE', 'TATTOOS', 'ETH_WINGS');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`NFT_metadata`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`NFT_metadata` (`id`, `title`, `data_url`, `tokenType`, `description`, `NFT_attributes_id`) VALUES (0, 'TOONZ #5842', 'http://degentoonz-app-gfcxi.ondigitalocean.app/asset/5842.png', 'ERC721', '8888 degenerate TOONZ that double as a membership to an exclusive metaverse community with the power to build it from the ground up.', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`NFT`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`NFT` (`id`, `contract_address`, `NFT_metadata_id`) VALUES (0, '0x19b86299c21505cdf59ce63740b240a9c822b5e4', 0);

COMMIT;

